// <auto-generated />
namespace BICT.Payetakht.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class A018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A018));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111129526_A018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
